platform :ios, '15.0'
use_frameworks!

def portals_pods
  pod 'IonicPortals', '0.14.0-rc.0'
  pod 'CapacitorCamera', '~> 8.0'
  pod 'IonicLiveUpdates', '~> 0.5.8'
  pod 'CapawesomeCapacitorLiveUpdate', :path => '../../node_modules/@capawesome/capacitor-live-update'
  pod 'CapawesomeCapacitorLiveUpdate/IonicProvider', :path => '../../node_modules/@capawesome/capacitor-live-update'

end

target 'Ecommerce' do
  portals_pods
end

target 'EcommerceLiveUpdates' do
  portals_pods
end

target 'EcommerceTests' do
  portals_pods
end
