platform :ios, '15.0'
use_frameworks!

def portals_pods
  pod 'IonicPortals', '~> 0.13.0'
  pod 'CapacitorCamera', '~> 8.0'
  pod 'IonicLiveUpdates', '~> 0.5.7'
end

target 'Ecommerce' do
  portals_pods
end

target 'EcommerceLiveUpdates' do
  portals_pods
end

target 'EcommerceTests' do
  portals_pods
end
